version: '3'

volumes:
  dev_mysql_data:

services:
  dev_mysql:
    container_name: dev_mysql
    image: mysql:5
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - ./mysql/conf/mysqld.cnf:/etc/mysql/my.cnf
      - dev_mysql_data:/var/lib/mysql
      - ./mysql/initsql:/docker-entrypoint-initdb.d

  dev_redis:
    container_name: dev_redis
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=passw0rd
    ports:
      - '6379:6379'